- generic [ref=e3]:
  - banner [ref=e4]:
    - generic [ref=e7]:
      - text: 
      - generic [ref=e8]:
        - link "" [ref=e9] [cursor=pointer]:
          - /url: "#"
          - generic [ref=e10]: 
        - link "" [ref=e11] [cursor=pointer]:
          - /url: "#"
          - generic [ref=e12]: 
        - link "" [ref=e13] [cursor=pointer]:
          - /url: "#"
          - generic [ref=e14]: 
        - link "" [ref=e15] [cursor=pointer]:
          - /url: "#"
          - generic [ref=e16]: 
  - generic [ref=e17]:
    - generic [ref=e18]:
      - heading "We Make Your Shopping Simple" [level=3]
      - heading "Practice Website for Rahul Shetty Academy Students" [level=1] [ref=e19]:
        - text: Practice Website for
        - emphasis [ref=e20]: Rahul Shetty Academy
        - text: Students
      - link "Register" [ref=e21] [cursor=pointer]:
        - /url: "#/auth/register"
    - generic [ref=e23]:
      - paragraph [ref=e24]:
        - generic [ref=e25]: Register to sign in with your personal account
      - generic [ref=e26]:
        - heading "Log in" [level=1] [ref=e27]
        - generic [ref=e28]:
          - generic [ref=e29]:
            - generic [ref=e30]: Email
            - textbox "email@example.com" [ref=e31]
          - generic [ref=e32]:
            - generic [ref=e33]: Password
            - textbox "enter your passsword" [ref=e34]
          - button "Login" [ref=e35] [cursor=pointer]
        - link "Forgot password?" [ref=e36] [cursor=pointer]:
          - /url: "#/auth/password-new"
        - paragraph [ref=e37] [cursor=pointer]: Don't have an account? Register here
  - generic [ref=e38]:
    - heading "Why People Choose Us?" [level=1] [ref=e41]
    - generic [ref=e42]:
      - generic [ref=e43]:
        - generic [ref=e45]: 
        - generic [ref=e46]:
          - heading "3546540" [level=1]
          - paragraph [ref=e47]: Successfull Orders
      - generic [ref=e48]:
        - generic [ref=e50]: 
        - generic [ref=e51]:
          - heading "37653" [level=1]
          - paragraph [ref=e52]: Customers
      - generic [ref=e53]:
        - generic [ref=e55]: 
        - generic [ref=e56]:
          - heading "3243" [level=1]
          - paragraph [ref=e57]: Sellers
    - generic [ref=e58]:
      - generic [ref=e59]:
        - generic [ref=e61]: 
        - generic [ref=e62]:
          - heading "4500+" [level=1]
          - paragraph [ref=e63]: Daily Orders
      - generic [ref=e64]:
        - generic [ref=e66]: 
        - generic [ref=e67]:
          - heading "500+" [level=1]
          - paragraph [ref=e68]: Daily New Customer Joining